### ISSUE TITLE
pb_download errors when curl status 401 even when public repo files actually download

### ISSUE THREAD

**Issue by monicathieu** [ropensci/piggyback#49] opened 2021-09-07 21:09 UTC
Hi there,

Before anything else, thank you for maintaining this package!

I've noticed some odd behavior when trying to use `pb_download()`. I have very little experience working with packages that interface with `curl` to download files from the GitHub API, so please pardon if I am confused or if these errors are not within the purview of the piggyback package itself!

I need to download all files from the latest release of a particular public repo. In this case, [cboettig/piggyback-tests](https://github.com/cboettig/piggyback-tests/releases/tag/v0.0.1) is an appropriate example repo.

If it helps, I have a Mac running Catalina and R 4.0.3.

**First,** leaving the `.token` argument of `pb_download()` as `get_token()` returns an error from `api_error_msg()` that "Cannot access release data for repository". The below call returns such an error:

```r
pb_download(repo = "cboettig/piggyback-tests")
```

I forked the package to follow the debug trace, and it appears that the default token generated by `get_token()` causes `gh::gh()` to return a 401 bad credentials error inside `release_info()`, making the whole function error out. Setting that argument to `NULL` by passing it in from the top allows `release_info()` to run all the way through, apparently because `gh::gh()` is okay with `.token = NULL` for public repos:

```r
pb_download(repo = "cboettig/piggyback-tests", .token = NULL)
```

This then allows the function to run all the way to the second error below, that feels very related in a way I don't understand fully.

**Second,** `gh_download_asset()`, when called on any given file in the release assets, successfully downloads the file through `httr::GET()` but still returns a status code of 401 such that `resp$status_code == 401`. This Unauthorized/Bad credentials status code causes `gh_download_asset()` to error out via `httr::stop_for_status(resp)`, BUT the associated file did actually successfully download! So the error in this case is not necessary, and in fact seems to prevent files from downloading that would work.

To test this in my fork, I tried changing that `httr::stop_for_status(resp)` call to `httr::warn_for_status(resp)`, and indeed warning messages get spit out but all of the files do download when I call:

```r
pb_download(repo = "cboettig/piggyback-tests", .token = NULL)
```

Clearly both of these are related to GitHub access token weirdness somehow, but I'm not sure how. Public repos should behave just fine with null tokens, and when I generated a personal access token for my own GitHub account and passed it in to `.token` it acted just the same as if I had left it as the default argument. That makes sense because I don't have special access to the public repo I'm trying to pull from anyway.

I don't know if `.token = NULL` and `httr::warn_for_status()` are the way to deal with these mysterious 401 errors/warnings, but they worked for me, in case that helps untangle this.

Thanks for reading!

**Comment by cboettig** [comment] 2021-09-07 23:21
Thanks very much for this!  Definitely weird, I cannot fully trace this either.  (I thought it might be due to the public token having been revoked, such that the command would fail with the default public token but work with `NULL`, but that's not it.  And can't explain the 401 error that's not an error either.)

In any event, I've replaced the behavior of the `get_token()` helper to simply call `gh::gh_token()` instead, which is based on `gitcreds` (so much nice new stuff from RStudio folks that didn't exist when `piggyback` first launched!).  It should still respect `GITHUB_TOKEN` or `GITHUB_PAT` env vars, but generally be safer and stay more consistent with current best practice than my old `get_token()`.  Can you test this out on the `gh_token()` branch?

```r
remotes::install_github("ropensci/piggyback@gh_token")
piggyback::pb_download(repo="cboettig/piggyback-tests")
```

**Comment by monicathieu** [comment] 2021-09-08 03:57
Thank you for the prompt response! Tested on my machine and it runs without errors or warnings on the `gh_token` branch! Very happy for the RStudio folks (and of course you in this case!) maintaining and improving the underlying stuff 😊

**Comment by bschilder** [comment] 2022-04-07 09:14
Hey @cboettig, thanks for the package!

I think i've been experiencing similar issues within my [MAGMA.Celltyping](https://github.com/neurogenomics/MAGMA_Celltyping) package:
- https://github.com/neurogenomics/MAGMA_Celltyping/issues/102
- https://github.com/neurogenomics/MAGMA_Celltyping/issues/105

Has this fix been pushed to CRAN yet?

That said, I also tried installing the dev branch but it didn't resolve the issues in my case:
`devtools::install_github("ropensci/piggyback@gh_token")`

**Comment by bschilder** [comment] 2022-04-07 10:33
I've added a temporary fix in the meantime, by showing an error message that indicates GItHub PATs are currently required to use `piggyback::pb_download` successfully:
https://github.com/neurogenomics/MAGMA_Celltyping/issues/102#issuecomment-1091528361

**Comment by cboettig** [comment] 2022-04-08 16:11
@bschilder hanks for the reminder, Looks like `master` branch is still ahead of CRAN.  I'll prep another release.  Are things working as expected if you install the `master` branch from GitHub?

The `gh_token` branch is stale from a previous merge and quite behind master (and CRAN I think).  I've deleted that branch now.

**Comment by bschilder** [comment] 2022-04-08 20:19
Ah, that makes sense now! 

Just tried `@master` instead of `@gh_token` in a new Docker container (without the GHA PAT) and I can confirm `piggyback::pb_download` works smoothly there:

```R
piggyback::pb_download(repo="cboettig/piggyback-tests")
```

A push to CRAN would be excellent. Thanks so much!

Best, 
Brian

**Comment by cboettig** [comment] 2022-05-19 18:04
should be resolved in most recent CRAN release.

**Closed as completed by cboettig** 2022-05-19 18:04 UTC
